#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running linters before push..."

# Запускаем Prettier

npm run format || {
	echo "❌ Prettier failed. Fix errors before pushing."
	exit 1
}

# Запускаем ESLint
npm run lint || {
	echo "❌ ESLint failed. Fix errors before pushing."
	exit 1
}

# Запускаем TypeScript проверку
npm run lint:ts || {
	echo "❌ TypeScript check failed. Fix type errors before pushing."
	exit 1
}

npm run build || {
	echo "❌ Build failed. Fix errors before pushing."
	exit 1
}

echo "✅ All checks passed!"
